<hr>

<div class="container p-4">
    <h1>Editar Patrocinador</h1>
    <form>
        <div class="mb-3">
            <label for="inputNome" class="form-label">Nome</label>
            <input type="text" class="form-control" id="inputNome" placeholder="Nome completo">
        </div>
        <div class="mb-3">
            <label for="inputDescricao" class="form-label">Descrição</label>
            <textarea class="form-control" id="inputDescricao" rows="4" placeholder="Breve descrição sobre o patrocinador"></textarea>
        </div>
        <div class="mb-3">
            <label for="inputTipo" class="form-label">Tipo do Patrocinio</label>
            <input type="text" class="form-control" id="inputTipo" placeholder="Patrocinador Ouro">
        </div>
        <div class="mb-3">
            <label for="inputLogo" class="form-label">URL da Logo</label>
            <input type="url" class="form-control" id="inputLogo" placeholder="https://exemplo.com/foto.jpg">
        </div>
        <div class="mb-3">
            <label for="inputFacebook" class="form-label">URL do Facebook</label>
            <input type="url" class="form-control" id="inputFacebook" placeholder="https://facebook.com/exemplo">
        </div>
        <div class="mb-3">
            <label for="inputInstagram" class="form-label">URL do Instagram</label>
            <input type="url" class="form-control" id="inputInstagram" placeholder="https://instagram.com/exemplo">
        </div>
        <div class="mb-3">
            <label for="inputWebSite" class="form-label">URL do WebSite</label>
            <input type="url" class="form-control" id="inputWebSite" placeholder="https://website.com/exemplo">
        </div>
        <button type="submit" class="btn btn-primary">Salvar Alterações</button>
        <a href="/admin/patrocinadores/listar" class="btn btn-secondary">Cancelar</a>
    </form>
</div>