
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">Admin</a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarAdmin">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarAdmin">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">
                        Usuários
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a class="dropdown-item" href="/admin/usuarios/cadastrar">
                                Cadastrar usuário
                            </a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="/admin/usuarios/listar">
                                Listar usuários
                            </a>
                        </li>
                    </ul>
                </li>


                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">
                        Palestrantes
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a class="dropdown-item" href="/admin/palestrantes/cadastrar">
                                Cadastrar palestrantes
                            </a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="/admin/palestrantes/listar">
                                Listar palestrantes
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">
                        Palestras
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a class="dropdown-item" href="/admin/palestras/cadastrar">
                                Cadastrar palestra
                            </a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="/admin/palestras/listar">
                                Listar palestras
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">
                        Patrocinadores
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a class="dropdown-item" href="/admin/patrocinadores/cadastrar">
                                Cadastrar Patrocinador
                            </a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="/admin/patrocinadores/listar">
                                Listar patrocinadores
                            </a>
                        </li>
                    </ul>
                </li>


                <li class="nav-item">
                    <a class="nav-link" href="/">Voltar pro site</a>
                </li>


                <li class="nav-item">
                    <a href="/admin/auth/logout" class="nav-link">
                     Sair
                    </a>
                </li>


            </ul>
        </div>
    </div>
</nav>
