<hr>

<div class="container p-4">
    <h1>Cadastrar Palestrante</h1>
    <form method="POST" action="/admin/palestrantes/cadastrar">
        <div class="mb-3">
            <label for="inputNome" class="form-label">Nome</label>
            <input type="text" name="nome" class="form-control" id="inputNome" placeholder="Nome completo" required>
        </div>
        <div class="mb-3">
            <label for="inputEmail" class="form-label">Email</label>
            <input type="email" name="email" class="form-control" id="inputEmail" placeholder="email@exemplo.com"
                required>
        </div>
        <div class="mb-3">
            <label for="inputEspecialidade" class="form-label">Especialidade</label>
            <input type="text" name="especialidade" class="form-control" id="inputEspecialidade"
                placeholder="Ex: Desenvolvimento Web, Data Science" required>
        </div>
        <button type="submit" class="btn btn-primary">Cadastrar</button>
        <a href="/admin/palestrantes/listar" class="btn btn-secondary">Cancelar</a>
    </form>
</div>