<hr>

<div class="container p-4">
    <div class="d-flex justify-content-between align-items-center mb-3">
        <h1>Listar Palestrantes</h1>
        <a href="/admin/palestrantes/cadastrar" class="btn btn-primary">+ Novo Palestrante</a>
    </div>
    <table class="table table-secondary table-striped-columns">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Nome</th>
                <th scope="col">Email</th>
                <th scope="col">Especialidade</th>
                <th scope="col">Ações</th>
            </tr>
        </thead>
        <tbody>

            <?php
                foreach ($palestrantes as $palestrante){
                    echo '
                    <tr>
                        <th scope="row">1</th>
                        <td>'.$palestrante['nome'].'</td>
                        <td>'.$palestrante['email'].'</td>
                        <td>'.$palestrante['especialidade'].'</td>
                        <td>
                            <a href="/admin/palestrantes/editar?id=1" class="btn btn-sm btn-warning">Editar</a>
                            <a href="/admin/palestrantes/excluir?id=1" class="btn btn-sm btn-danger">Excluir<a>
                </td>
            </tr>
                    ';
                }
            ?>

        </tbody>
    </table>
</div>