<div class="container">
    <section class="mt-4 p-4 border border-2 border-sucess rounded ">
        <div class="d-flex justify-content-between align-items-center">
            <h1 class=""><i class="bi bi-people-fill"></i> Palestrantes</h1>
            <button class="btn btn-primary"><i class="bi bi-plus-lg"></i> Novo Palestrante</button>
        </div>
        <table class="table table-striped table-hover ">
            <thead>
                <tr>
                    <th class="text-start" scope="col">#</th>
                    <th class="text-center" scope="col">Foto</th>
                    <th class="text-center" scope="col">Nome</th>
                    <th class="text-center" scope="col">E-mail</th>
                    <th class="text-end" scope="col">Ações</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th class="text-start" scope="row">1</th>
                    <td class="text-center">Mark</td>
                    <td class="text-center">Otto</td>
                    <td class="text-center">@mdo</td>
                    <td class="text-end">
                        <button class="btn btn-warning">
                            <i class="bi bi-pencil-square"></i>
                        </button>
                        <button class="btn btn-danger">
                            <i class="bi bi-trash3"></i>
                        </button>
                    </td>
                </tr>
                <tr>
                    <th class="text-start" scope="row">2</th>
                    <td class="text-center">Jacob</td>
                    <td class="text-center">Thornton</td>
                    <td class="text-center">@fat</td>
                    <td class="text-end">
                        <button class="btn btn-warning">
                            <i class="bi bi-pencil-square"></i>
                        </button>
                        <button class="btn btn-danger">
                            <i class="bi bi-trash3"></i>
                        </button>
                    </td>
                </tr>
                <tr>
                    <th class="text-start" scope="row">3</th>
                    <td class="text-center">John</td>
                    <td class="text-center">Doe</td>
                    <td class="text-center">@social</td>
                    <td class="text-end">
                        <button class="btn btn-warning">
                            <i class="bi bi-pencil-square"></i>
                        </button>
                        <button class="btn btn-danger">
                            <i class="bi bi-trash3"></i>
                        </button>
                    </td>
                </tr>
            </tbody>
        </table>
    </section>
</div>