<hr>

<div class="container p-4">
	<h1>Editar Palestras</h1>
	<form>
		
		<div class="mb-3">
			<label for="inputTitulo" class="form-label">Titulo</label>
			<input type="email" class="form-control" id="inputEmail" placeholder="email@exemplo.com">
		</div>
		<div class="mb-3">
			<label for="inputDescricao" class="form-label">Descrição</label>
			<input type="text" class="form-control" id="inputEspecialidade"
				placeholder="Ex: Desenvolvimento Web, Data Science">
		</div>
		<div class="mb-3">
			<label for="inputPalestra" class="form-label">Artista</label>
			<input class="form-control" id="inputBiografia" rows="4"
				placeholder="Breve descrição sobre o palestrante"></input>
		</div>
		<div class="mb-3">
			<label for="inputHorario" class="form-label">Horario</label>
			<input type="time" class="form-control" id="inputHorario" rows="4"
				placeholder="Breve descrição sobre a palestra"></input>
		</div>
		<button type="submit" class="btn btn-success">Salvar Alterações</button>
		<a href="/admin/palestras/listar" class="btn btn-secondary">Cancelar</a>
	</form>
</div>