<hr>

<div class="container p-4">
    <h1>Editar Usuario</h1>
    <form method="POST" action="/admin/usuarios/editar?id=<?= $usuario->id ?>">
        <div class="mb-3">
            <label for="inputNome" class="form-label">Nome</label>
            <input type="text" name="nome" class="form-control" id="inputNome" value="<?= htmlspecialchars($usuario->nome) ?>">
        </div>
        <div class="mb-3">
            <label for="inputEndereco" class="form-label">Endereço</label>
            <input type="text" name="endereco" class="form-control" id="inputEndereco" value="<?= htmlspecialchars($usuario->endereco) ?>">
        </div>
        <div class="mb-3">
            <label for="inputEmail" class="form-label">Endereço de Email</label>
            <input type="email" name="email" class="form-control" id="inputEmail" value="<?= htmlspecialchars($usuario->email) ?>">
        </div>
        <button type="submit" class="btn btn-success">Salvar Alterações</button>
        <a href="/admin/usuarios/listar" class="btn btn-secondary">Cancelar</a>
    </form>
</div>
