<style>
    .text-php {
        color: #563529  !important;
    }
</style>
<div class="container min-vh-100 d-flex justify-content-center align-items-center">
        <div class="row justify-content-center w-100 ">
            <div class="col-12 col-md-6 col-lg-4">
                
                <div class="card border-0 shadow-lg rounded-4 p-4 bg-white">
                    <div class="card-body text-center">
                        
                        <h2 class="fw-bold text-primary mb-0 text-php">PHP com Rapadura</h2>
                        <p class="text-secondary small mb-4">Sistema de Gestão de Eventos</p>

                        <form class="text-start" method="POST" >
                            
                            <div class="mb-3">
                                <label for="usuario" class="form-label fw-semibold text-dark small">Email</label>
                                <input type="text" name="email" class="form-control bg-light border-light-subtle py-2" id="usuario" placeholder="Digite seu email">
                            </div>

                            <div class="mb-4">
                                <label for="senha" class="form-label fw-semibold text-dark small">Senha</label>
                                <div class="input-group">
                                    <input type="password" name="password" class="form-control bg-light border-light-subtle border-end-0 py-2" id="senha" placeholder="Digite sua senha">
                                    <span class="input-group-text bg-light border-light-subtle border-start-0" style="cursor: pointer;">
                                    </span>
                                </div>
                            </div>

                            <div class="d-grid">
                                <button type="submit" class="btn btn-primary text-white fw-semibold py-2 rounded-3 shadow-sm">Entrar</button>
                            </div>

                        </form>

                    </div>
                </div>

            </div>
        </div>
    </div>