<hr>

<div class="container p-4">
    <h1>Cadastrar Palestra</h1>
    <form method="POST">
        <div class="mb-3">
            <label for="inputTitulo" class="form-label">Título da Palestra</label>
            <input type="text" name="titulo" class="form-control" id="inputTitulo" placeholder="Ex: Padrões de Projeto em PHP" required>
        </div>
        <div class="mb-3">
            <label for="inputPalestrante" class="form-label">Nome do Palestrante</label>
            <input type="text" name="palestrante" class="form-control" id="inputPalestrante" placeholder="Nome do palestrante" required>
        </div>
        <div class="mb-3">
            <label for="inputHorario" class="form-label">Horário</label>
            <input type="time" name="horario" class="form-control" id="inputHorario" required>
        </div>
        <div class="mb-3">
            <label for="inputDescricao" class="form-label">Descrição</label>
            <textarea name="descricao" class="form-control" id="inputDescricao" rows="4" placeholder="Sobre o que será a palestra?" required></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Cadastrar Palestra</button>
        <a href="/admin/palestras/listar" class="btn btn-secondary">Cancelar</a>
    </form>
</div>